In [1]:
import numpy as np

np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])

# 陣列相加
print(np1 + np2)  # [4 6 8]

# 顯示相關資訊
print(np1.ndim, np1.shape, np1.dtype)  # 1 (3,) int64 => 一維陣列, 三個元素, 資料型別

[4 6 8]
1 (3,) int32


In [2]:
# dimension shape datatype
np3 = np.array([1, 2, 3, 4, 5, 6])
np3 = np3.reshape([2, 3])
print(np3.ndim, np3.shape, np3.dtype)  # 2 (2, 3) int64



2 (2, 3) int32


In [15]:
# method to create array
np4 = np.zeros([2, 3])  # array([[ 0.,  0.,  0.], [ 0.,  0.,  0.]])
np5 = np.ones([2, 3])  # array([[ 1.,  1.,  1.], [ 1.,  1.,  1.]])
np6 = np.full([3,5],9)
np7 = np.random.random([2,4])
np8 = np.eye(5)

In [4]:
# reshape
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3[2])  # 3

np3 = np3.reshape([2, 3])
print(np3[1, 0])  # 4

3
4


In [5]:
# mask
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3 > 3)  # [False False False  True  True  True]
print(np3[np3 > 3])  # [4 5 6]
np3 = np3.reshape([2, 3])
print(np3.sum(axis=1))  # 將 axis=1 橫向加總 [6 15]

[False False False  True  True  True]
[4 5 6]
[ 6 15]


In [11]:
# slicing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:1,0:3]

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
